### ISSUE TITLE
Code blocks should not wrap lines but instead scroll horizontally

### ISSUE THREAD

**Issue by ryanewtaylor** [matcornic/hugo-theme-learn#81]
# Current Behavior

When I create the following code block

```markdown
2. Install Chocolatey

    ```powershell
    Set-ExecutionPolicy Bypass
    iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
    ```
```

It is subsequently rendered like so.

![image](https://user-images.githubusercontent.com/1215819/31465702-b316f1be-aea2-11e7-83a4-056463017d3f.png)

Note that the second line soft wraps to the next line because it is too long to fit in the content area.

# Expected Behavior

The rendered code block should display a horizontal scrollbar if its content cannot fit within the available space rather than wrapping the content.

**Comment by matcornic** [comment]
Hey @ryanewtaylor 

It's a matter of taste, but I think I'm on your side 😄 !

Would you like to make a PR ?

**Comment by ryanewtaylor** [comment]
Sure, I can take a crack at it.

**Comment by siddhantrimal** [comment]
Or, just line numbers would be great. Personally, I wrap lines but the lines are distinct with line-numbers on Sublime Text. Works great; does the job. There are [plugins](https://github.com/wcoder/highlightjs-line-numbers.js/) for Highlight.js

**Comment by pgorod** [comment]
Did anybody get the line numbers working with that plugin, `highlightjs-line-numbers`?

I can get the file, but I'm trying to follow the instructions on their readme, 

> Download plugin and include file after highlight.js:
> `<script src="path/to/highlight.min.js"></script>`
> `<script src="path/to/highlightjs-line-numbers.min.js"></script>`

and I can't find where Learn theme is including that source...

**Comment by mattcbaker** [comment]
Did the horizontal scroll ever get added?

**Comment by matalo33** [comment]
Your code block above is rendering with horizontal scroll for me. Possible this has been fixed in the time since the ticket was opened.
Can you confirm @ryanewtaylor ?

**Comment by Boris-Rasin** [comment]
This still doesn't work. The block above is rendered with scrollbar by github, learn still wraps the lines.

**Comment by Boris-Rasin** [comment]
This add horizontal scrollbar:
**layouts/partials/custom-header.html**
```css
<style type="text/css">
pre code {
    white-space: pre;
}
</style>
```

**Comment by iashyam** [comment]
In your css where you have `pre code` check this:

```css
overflow: auto;
```
This would add a horizontal scrollbar.
